version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tamtam_bot
      MYSQL_USER: bot
      MYSQL_PASSWORD: botpass
    ports:
      - "3306:3306"
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
